//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payment.db
{
    using Payment.Models;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DoAnCuoiKiiEntities1 : DbContext
    {
        public DoAnCuoiKiiEntities1()
            : base("name=DoAnCuoiKiiEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KeToan> KeToans { get; set; }
        public virtual DbSet<Phieunhapkho> Phieunhapkhoes { get; set; }
        public virtual DbSet<Phieuxuatkho> Phieuxuatkhoes { get; set; }
        public virtual DbSet<Sanpham> Sanphams { get; set; }
        public virtual DbSet<daily> dailies { get; set; }
        public virtual DbSet<Donhang> Donhangs { get; set; }
        public virtual DbSet<Info> Info { get; set; }

    }
}
