//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payment.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donhang
    {
        public string maDonhang { get; set; }
        public string tensanpham { get; set; }
        public string tenDaily { get; set; }
        public Nullable<double> gia { get; set; }
        public Nullable<int> soluong { get; set; }
    
        public virtual daily daily { get; set; }
    }
}
