//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payment.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeToan
    {
        public string maID { get; set; }
        public string Tenketoan { get; set; }
        public string Diachi { get; set; }
        public Nullable<int> sodienthoai { get; set; }
    }
}
