//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payment.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phieuxuatkho
    {
        public string maPhieuxuat { get; set; }
        public Nullable<System.DateTime> ngayxuat { get; set; }
        public Nullable<double> giaca { get; set; }
        public Nullable<int> soluong { get; set; }
        public string maDonhang { get; set; }
        public string maID { get; set; }
    }
}
