//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payment.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sanpham
    {
        public string maSanpham { get; set; }
        public string theloai { get; set; }
        public Nullable<double> giatien { get; set; }
        public string tensanpham { get; set; }
    }
}
